import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const dmsans = localFont({
  src: "../../public/fonts/DMSans-VariableFont_opsz,wght.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Imersão Viver de IA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${dmsans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
